version: '3'

services:
  postgres:
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "${POSTGRES_USER}" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: on-failure
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
  web:
    command: bash -c "while !</dev/tcp/postgres/5432;do sleep 1; done; npm run build; npm run typeorm:run; npm run start"
    image: 'riinavi/users-api:latest'
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - S3_API_KEY=${S3_API_KEY}
      - S3_API_SECRET=${S3_API_SECRET}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET=${S3_BUCKET}
      - LOG_GROUP=${LOG_GROUP}
      - SERVER_IP=${SERVER_IP}
    ports:
      - 8080:8080
